name: Android CI - Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Verify PR Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project with Gradle (PR check)
        run: ./gradlew assembleDebug
